replicaCount: 1
name: order-service

image:
  repository: order-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: dockerhub-creds

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chinthika-rathnayake.click
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

newrelic:
  licenseKey: YOUR_NEWRELIC_LICENSE_KEY
  appName: order-service-prod

resources: { }

affinity: { }